name: one_chat
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any

  # https://pub.dev/packages/get
  get: ^4.6.5
  # https://pub.dev/packages/get_storage
  get_storage: ^2.1.1
  # https://pub.dev/packages/dio
  dio: ^5.3.2
  window_manager: ^0.3.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  flex_color_scheme: ^7.1.2
  flutter_easyloading: ^3.0.5
  uuid: ^4.2.1
  path_provider: ^2.1.1
  flutter_slidable: ^3.0.1
  moment_dart: ^1.0.1
  flutter_svg: ^2.0.7

  flutter_highlighter: ^0.1.1

  http: ^1.1.0

  rxdart: ^0.27.7

  flutter_tiktoken: ^0.0.1

  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^5.0.1

  # https://pub.dev/packages/logger
  logger: ^2.0.2

  # https://pub.dev/packages/flutter_dotenv
  flutter_dotenv: ^5.1.0

  # https://pub.dev/packages/flutter_styled_toast
  flutter_styled_toast: ^2.2.1

  # https://pub.dev/packages/custom_pop_up_menu
  custom_pop_up_menu: ^1.2.4

  url_launcher: ^6.1.14

  # https://pub.dev/packages/markdown_widget
  markdown_widget: ^2.3.2+2

  # https://pub.dev/packages/flutter_math_fork
  flutter_math_fork: ^0.7.2

  # https://pub.dev/packages/dart_openai
  dart_openai: ^5.0.0

  # https://pub.dev/packages/extended_image
  extended_image: ^8.2.0
  # https://pub.dev/packages/loading_progress
  loading_progress: ^1.0.2

  # https://pub.dev/packages/file_selector
  file_selector: ^1.0.1

  # https://pub.dev/packages/image_gallery_saver
  image_gallery_saver: "^2.0.3"

  # https://pub.dev/packages/badges
  badges: ^3.1.2

  # https://pub.dev/packages/image
  image: ^4.1.3

  # https://pub.dev/packages/file_picker
  file_picker: ^6.1.1

  # https://pub.dev/packages/langchain_google
  langchain_google: ^0.2.1+2
  langchain: ^0.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6
  analyzer: ^5.13.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/chatgpt-grey.svg
    - assets/google-grey.svg
    - assets/locales/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icon-ios.png"
  image_path_android: "assets/icon-android.png"
  min_sdk_android: 21